export const GET_COMPANIES = Symbol('GET_COMPANIES');
export const GET_PROJECTS_BY_COMPANY_ID = Symbol('GET_PROJECTS_BY_COMPANY_ID');
export const GET_EMPLOYEES_BY_COMPANY_ID = Symbol('GET_EMPLOYEES_BY_COMPANY_ID');
export const GET_COMPANY_ADDRESS = Symbol('GET_COMPANY_ADDRESS');
export const GET_EMPLOYEE_BY_ID = Symbol('GET_EMPLOYEE_BY_ID');