export const FIELD_CHANGE = Symbol('FIELD_CHANGE');
export const CREATE_PROJECT = Symbol('CREATE_PROJECT');
export const GET_ALL_EMPLOYEES = Symbol('GET_ALL_EMPLOYEES');
export const HANDLE_TOGGLE = Symbol('HANDLE_TOGGLE');
export const ASSIGN_EMPLOYEES_TO_PROJECT = Symbol('ASSIGN_EMPLOYEES_TO_PROJECT');
export const REMOVE_EMPLOYEES_FROM_PROJECT = Symbol('REMOVE_EMPLOYEES_FROM_PROJECT');